services:
  web:
    build: .
    working_dir: /api_source
    networks: 
      - shared_network
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/api_source
    
networks:
  shared_network:
    external: true
