# Generated by Django 4.0.10 on 2023-07-10 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_measurement_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
