# Generated by Django 4.0.10 on 2023-07-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_alter_measurement_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actuator',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
