# Generated by Django 4.0.10 on 2023-07-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_actuator_end_time_actuator_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.crop'),
        ),
    ]
